# This is a basic workflow that is manually triggered

name: Publish Container Update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Upload Python Package"]
    types: [completed]

jobs:
  update_container:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python3.7 -m pip install --upgrade pip
        python3.7 -m pip install virtualenv

        sudo add-apt-repository -y ppa:ubuntugis/ppa \
        && sudo apt install -y \
          gdal-bin libgdal-dev
    - name: Update dependencies
      run: |
        git clone https://${{ secrets.ADO_USER }}:${{ secrets.ADO_PASSWORD }}@cloudes.visualstudio.com/CDPX/_git/CDPX-Linux-Images
        cd CDPX-Linux-Images

        cd src/user/agai/agai-template-ubuntu-1804/latest/requirements
        
        install_all="ai-python[core,ama,reco,msft-utils,retail,energy-ca,energy-km,fclib,fsi-nlp,fsi-risk,fsi,gem-ent,gem-reco,gem,sc-ro,sc-ip,sc-ecr,sc,cdm,maro,all]"
        install_test="ai-python[test]"

        cat install_all > core.in
        cat install_test > test.in

        ./generate.sh -s .

        git config --global user.email "dciborow@microsoft.com"
        git config --global user.name "Daniel Ciborowski"

        git add -A
        git commit -m "Updating Container"

        git push origin --force master:dciborow/updateContainer
    - name: HTTP Request Action
      uses: fjogeleit/http-request-action@v1.8.0
      with:
        url: 'https://cloudes.visualstudio.com/CDPX/_apis/git/repositories/CDPX-Linux-Images/pullrequests?api-version=6.0'
        method: 'POST'
        username: "dciborow"
        password: ${{ secrets.ADO_PAT }}
        data: '{"targetRefName": "refs/heads/master", "sourceRefName": "refs/heads/dciborow/updateContainer", "title": "Dependancy Update", "autoCompleteSetBy": "dciborow@microsoft.com"}'
        ignoreStatusCode: '409'
